name: CI Tests

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  test-jvm:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/setup-java@v1.4.3
        with:
          java-version: "11"

      - uses: actions/checkout@v2

      - name: Build
        run: ./gradlew compileTestKotlinJvm compileKotlinJvm

      - name: Run JVM tests
        run: ./gradlew jvmTest

  test-linux:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build
        run: ./gradlew linkDebugTestLinuxX64

      - name: Run Linux tests
        run: ./gradlew linuxX64Test

  test-macos:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build
        run: ./gradlew linkDebugTestMacosX64

      - name: Run macOS tests
        run: ./gradlew macosX64Test
