name: CI Tests

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-jvm:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/setup-java@v1.4.3
        with:
          java-version: "11"

      - uses: actions/checkout@v2

      - name: JVM tests
        run: ./gradlew jvmTest
