name: Linux Tests

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  test-linux:
    runs-on: ubuntu-latest
    #timeout-minutes: 30

    steps:
      - uses: actions/checkout@v2

      - name: Build
        run: ./gradlew linkDebugTestLinuxX64

      - name: Run Linux tests
        run: ./gradlew linuxX64Test
        #timeout-minutes: 10
