name: CI Tests

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  test-jvm:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - uses: actions/setup-java@v1.4.3
        with:
          java-version: "11"

      - uses: actions/checkout@v2

      - name: Build
        run: ./gradlew jvmTestClasses

      - name: Run JVM tests
        run: ./gradlew jvmTest
        timeout-minutes: 10

  test-linux:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v2

      - name: Build
        run: ./gradlew linkDebugTestLinuxX64

      - name: Run Linux tests
        run: ./gradlew linuxX64Test
        timeout-minutes: 10
